version: 2

project_name: side-eye

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/side-eye
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goarch:
      - amd64
      - arm64

archives:
  - format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  abbrev: 7

release:
  extra_files:
    - glob: ./scripts/install.sh
